services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: wp-bedrock-app
    container_name: wp-bedrock-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - wp-bedrock

  webserver:
    image: nginx:latest
    container_name: nginx-webserver
    restart: unless-stopped
    ports:
      - "${APP_PORT}"

    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - wp-bedrock

  db:
    image: mysql:latest
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - wp-bedrock

networks:
  wp-bedrock:

volumes:
  dbdata:
